{% set name = "exrex" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59912f0234567a5966b10d963c37ca9fe07f1640fd158e77c0dc7c3aee780489

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - exrex

about:
  home: https://exrex.readthedocs.io/
  license: AGPL v3.0
  license_family: GPL
  license_file: COPYING
  summary: Irregular methods on regular expressions
  description: |
    Exrex is a command line tool and python module that generates all - or random -
    matching strings to a given regular expression and more. It's pure python, without
    external dependencies.

    There are regular expressions with infinite matching strings (eg.: [a-z]+),
    in these cases exrex limits the maximum length of the infinite parts.

    Exrex uses generators, so the memory usage does not depend on the number of
    matching strings.
  doc_url: https://exrex.readthedocs.io/
  dev_url: https://github.com/asciimoo/exrex

extra:
  recipe-maintainers:
    - scopatz
